//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch coisane.rc
//
#define IDD_WIZARD_PAGE_SERVER          801
#define IDS_WIZARD_PAGE_SERVER_HEADER_TITLE 802
#define IDD_PROPERTIES                  803
#define IDS_WIZARD_PAGE_SERVER_HEADER_SUBTITLE 803
#define IDD_WIZARD_PAGE_SCANNER         804
#define IDS_WIZARD_PAGE_SCANNER_HEADER_TITLE 804
#define IDS_WIZARD_PAGE_SCANNER_HEADER_SUBTITLE 805
#define IDC_WIZARD_PAGE_SERVER_EDIT_HOST 1000
#define IDC_WIZARD_PAGE_SERVER_EDIT_PORT 1001
#define IDC_WIZARD_PAGE_SERVER_TEXT_HOST 1002
#define IDC_WIZARD_PAGE_SERVER_TEXT_PORT 1003
#define IDC_WIZARD_PAGE_SERVER_TEXT_INFO 1004
#define IDC_PROPERTIES_COMBO_SCANNER    1008
#define IDC_PROPERTIES_TEXT_SCANNER     1009
#define IDC_PROPERTIES_GROUP_CREDENTIALS 1010
#define IDC_PROPERTIES_TEXT_USERNAME    1011
#define IDC_PROPERTIES_EDIT_USERNAME    1012
#define IDC_PROPERTIES_TEXT_PASSWORD    1013
#define IDC_PROPERTIES_EDIT_PASSWORD    1014
#define IDC_PROPERTIES_BUTTON_CHECK     1015
#define IDC_PROPERTIES_BUTTON_RESET     1016
#define IDC_PROPERTIES_TEXT_INFO        1017
#define IDC_WIZARD_PAGE_SCANNER_TEXT_INFO 1017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        804
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           802
#endif
#endif
