//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch coisane.rc
//
#define IDD_WIZARD_PAGE_SERVER          801
#define IDS_WIZARD_PAGE_SERVER_HEADER_TITLE 802
#define IDD_PROPERTIES                  803
#define IDS_WIZARD_PAGE_SERVER_HEADER_SUBTITLE 803
#define IDD_WIZARD_PAGE_SCANNER         804
#define IDS_WIZARD_PAGE_SCANNER_HEADER_TITLE 804
#define IDS_WIZARD_PAGE_SCANNER_HEADER_SUBTITLE 805
#define IDD_WIZARD_PAGE_PROGRESS        805
#define IDS_PROPERTIES_SCANNER_DEVICE   806
#define IDS_PROPERTIES_SCANNER_CHECK_SUCCESSFUL 807
#define IDS_PROPERTIES_SCANNER_CHECK_FAILED 808
#define IDS_PROPERTIES_SCANNER_RESET_SUCCESSFUL 809
#define IDS_PROPERTIES_SCANNER_RESET_FAILED 810
#define IDS_DEVICE_OPEN_FAILED          811
#define IDS_DEVICE_FIND_FAILED          812
#define IDS_SESSION_INIT_FAILED         813
#define IDS_SESSION_CONNECT_FAILED      814
#define IDS_SESSION_STEP_CONNECT        815
#define IDS_SESSION_STEP_INIT           816
#define IDS_DEVICE_STEP_FIND            817
#define IDS_DEVICE_STEP_OPEN            818
#define IDC_WIZARD_PAGE_SERVER_EDIT_HOST 1000
#define IDC_WIZARD_PAGE_SERVER_EDIT_PORT 1001
#define IDC_WIZARD_PAGE_SERVER_TEXT_HOST 1002
#define IDC_WIZARD_PAGE_SERVER_TEXT_PORT 1003
#define IDC_WIZARD_PAGE_SERVER_TEXT_INFO 1004
#define IDC_PROPERTIES_COMBO_SCANNER    1008
#define IDC_PROPERTIES_TEXT_SCANNER     1009
#define IDC_PROPERTIES_GROUP_CREDENTIALS 1010
#define IDC_PROPERTIES_TEXT_USERNAME    1011
#define IDC_PROPERTIES_EDIT_USERNAME    1012
#define IDC_PROPERTIES_TEXT_PASSWORD    1013
#define IDC_PROPERTIES_EDIT_PASSWORD    1014
#define IDC_PROPERTIES_BUTTON_CHECK     1015
#define IDC_PROPERTIES_BUTTON_RESET     1016
#define IDC_PROPERTIES_TEXT_INFO        1017
#define IDC_WIZARD_PAGE_SCANNER_TEXT_INFO 1017
#define IDC_WIZARD_PAGE_SCANNER_COMBO_SCANNER 1019
#define IDC_WIZARD_PAGE_SCANNER_TEXT_USERNAME 1020
#define IDC_WIZARD_PAGE_SCANNER_EDIT_USERNAME 1021
#define IDC_WIZARD_PAGE_SCANNER_TEXT_PASSWORD 1022
#define IDC_WIZARD_PAGE_SCANNER_EDIT_PASSWORD 1023
#define IDC_WIZARD_PAGE_SCANNER_GROUP_CREDENTIALS 1024
#define IDC_WIZARD_PAGE_PROGRESS_ANIMATE 1025
#define IDC_WIZARD_PAGE_PROGRESS_LABEL  1026
#define IDC_WIZARD_PAGE_PROGRESS_TEXT_MAIN 1026
#define IDC_WIZARD_PAGE_PROGRESS_TEXT_SUB 1027
#define IDC_PROPERTIES_TEXT_MAIN        1028
#define IDC_WIZARD_PAGE_PROGRESS_ICON   1029
#define IDC_PROPERTIES_ICON             1030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        806
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           802
#endif
#endif
